import { validateApiKey, unauthorized } from "@/lib/auth";
import { getServiceSupabase } from "@/lib/supabase";
import { getGitHubClient, parseRepo } from "@/lib/github";
import { corsPreflight, withCors } from "@/lib/cors";
import { BamlValidationError } from "@boundaryml/baml";
import type { ConversationTurn, PanelSubmission, SubmissionMetadata } from "@consiliency/panel-types";

export async function OPTIONS(req: Request) { return corsPreflight(req); }

const MAX_TURN_CONTENT_LENGTH = 4000;

/**
 * Sanitize user-supplied transcript content before passing to BAML.
 * Prevents prompt injection via oversized or control-character-laden strings.
 */
function sanitizeTranscript(turns: ConversationTurn[]): ConversationTurn[] {
  return turns.map((turn) => ({
    ...turn,
    content: turn.content
      // eslint-disable-next-line no-control-regex
      .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "") // strip non-printable control chars
      .slice(0, MAX_TURN_CONTENT_LENGTH),
  }));
}

function sseEvent(data: object): string {
  return `data: ${JSON.stringify(data)}\n\n`;
}

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
): Promise<Response> {
  const key = await validateApiKey(req);
  if (!key) return withCors(unauthorized(), req);

  const { id } = await params;
  const body = (await req.json()) as { repo: string; panelRepo?: string };

  const supabase = getServiceSupabase();

  // Atomically transition pending/failed → processing (idempotency guard)
  const { data: updated } = await supabase
    .from("panel_submissions")
    .update({ status: "processing" })
    .eq("id", id)
    .in("status", ["pending", "failed"])
    .select("id")
    .maybeSingle();

  if (!updated) {
    // Already processing or completed — check which
    const { data: existing } = await supabase
      .from("panel_submissions")
      .select("status")
      .eq("id", id)
      .single();

    if (existing?.status === "completed") {
      // Return the existing issue as an SSE completed event
      const { data: existingIssue } = await supabase
        .from("panel_issues")
        .select("github_issue_url, github_issue_number, plain_summary")
        .eq("submission_id", id)
        .order("created_at", { ascending: true })
        .limit(1)
        .single();

      if (existingIssue) {
        const enc = new TextEncoder();
        const replayStream = new ReadableStream({
          start(ctrl) {
            ctrl.enqueue(enc.encode(sseEvent({
              type: "completed",
              message: "Issue already created",
              issueUrl: existingIssue.github_issue_url,
              issueNumber: existingIssue.github_issue_number,
              plainSummary: existingIssue.plain_summary,
            })));
            ctrl.close();
          },
        });
        return withCors(new Response(replayStream, {
          headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" },
        }), req);
      }
    }
    return withCors(Response.json({ error: "Submission already being processed" }, { status: 409 }), req);
  }

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: object) => {
        controller.enqueue(encoder.encode(sseEvent(data)));
      };

      try {
        // Fetch the submission
        const { data: submission } = await supabase
          .from("panel_submissions")
          .select("*")
          .eq("id", id)
          .single();

        if (!submission) {
          send({ type: "error", message: "Submission not found" });
          controller.close();
          return;
        }

        const sub = submission as PanelSubmission;
        const navigationBreadcrumb = (sub as any).navigation_breadcrumb as Array<{url: string; title: string; ts: string}> | null;
        const componentHint = (sub as any).component_hint as string | null;
        const attachmentUrls = (sub as any).attachment_urls as Array<{url: string; type: string; name: string}> | null;
        const consoleErrors = (sub as any).console_errors as string[] | null;
        const consoleWarnings = (sub as any).console_warnings as string[] | null;

        // Import the BAML client generated by baml-cli generate
        // Path: baml_client/ at repo root → 6 levels up from this route file
        const { b } = await import("baml_client");

        const bamlMetadata = sub.metadata as SubmissionMetadata;

        // ── Routing: decide target repo ──────────────────────────────────────────
        let targetRepo = body.repo;
        if (body.panelRepo) {
          const retainedKinds = (attachmentUrls ?? [])
            .filter(a => a.type === "screenshot")
            .map(a => {
              if (a.name.startsWith("screenshot-page")) return "page" as const;
              if (a.name.startsWith("screenshot-panel")) return "panel" as const;
              return null;
            })
            .filter((k): k is "page" | "panel" => k !== null);

          send({ type: "progress", message: "Routing to correct repo…" });
          const routing = await b.RouteToRepo(
            sanitizeTranscript(sub.transcript as ConversationTurn[]),
            bamlMetadata,
            retainedKinds,
          );
          targetRepo = routing.target === "panel" ? body.panelRepo : body.repo;
          send({ type: "routing", target: routing.target, targetRepo, confidence: routing.confidence });
        }

        // Fetch repo context for enrichment
        send({ type: "progress", message: "Gathering repository context…" });

        const { owner, repo } = parseRepo(targetRepo);
        const octokit = getGitHubClient(sub.tier as "guest" | "contractor" | "team");

        const [{ data: labels }, { data: issues }] = await Promise.all([
          octokit.issues.listLabelsForRepo({ owner, repo, per_page: 50 }),
          octokit.issues.listForRepo({ owner, repo, state: "open", per_page: 20 }),
        ]);

        const repoContext = {
          labels: labels.map((l) => ({ name: l.name, description: l.description ?? undefined, color: l.color })),
          recentIssues: issues.map((i) => ({ number: i.number, title: i.title, state: i.state, url: i.html_url })),
        };

        send({ type: "progress", message: "Classifying issue…" });

        let issueInput = {
          transcript: sanitizeTranscript(sub.transcript as ConversationTurn[]),
          metadata: bamlMetadata,
          repo_context: repoContext,
          tier: sub.tier,
          console_errors: consoleErrors ?? undefined,
          console_warnings: consoleWarnings ?? undefined,
          // Map ts → timestamp to match BAML NavigationEntry schema
          navigation_breadcrumb: navigationBreadcrumb
            ? navigationBreadcrumb.map(e => ({ url: e.url, title: e.title, timestamp: e.ts }))
            : undefined,
          component_hint: componentHint ?? undefined,
          attachment_urls: attachmentUrls ?? undefined,
        };

        const classification = await b.ClassifyIssue(issueInput);

        send({ type: "progress", message: "Enriching with context…" });
        const enrichment = await b.EnrichWithRepoContext(issueInput, classification);

        // For team tier: fetch relevant file contents and run fix analysis
        let fixSuggestion: { relevant_functions: string[]; root_cause: string; suggested_approach: string; code_hint?: string | null; confidence: string } | null = null;

        if (sub.tier === "team" && enrichment.relevant_files.length > 0) {
          send({ type: "progress", message: "Analysing source files…" });

          const FILE_LIMIT = 5;
          const CONTENT_LIMIT = 8000;
          const filesToFetch = enrichment.relevant_files.slice(0, FILE_LIMIT);
          const fileContents: Record<string, string> = {};

          await Promise.allSettled(
            filesToFetch.map(async (filePath) => {
              try {
                const { data } = await octokit.repos.getContent({ owner, repo, path: filePath });
                if ("content" in data && typeof data.content === "string") {
                  const decoded = Buffer.from(data.content, "base64").toString("utf8");
                  fileContents[filePath] = decoded.slice(0, CONTENT_LIMIT);
                }
              } catch {
                // file not found or not a file — skip silently
              }
            })
          );

          if (Object.keys(fileContents).length > 0) {
            issueInput = {
              ...issueInput,
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              repo_context: { ...repoContext, file_contents: fileContents } as any,
            };
            fixSuggestion = await b.SuggestFix(issueInput, classification, enrichment);
          }
        }

        send({ type: "progress", message: "Formatting issue…" });
        type FormattedIssue = {
          github_title: string;
          github_body: string;
          labels: string[];
          assignee?: string;
          plain_summary: string;
          technical_details: string;
          priority: string;
        };
        let issueOutput: FormattedIssue;
        try {
          issueOutput = await b.FormatAsGitHubIssue(issueInput, classification, enrichment, fixSuggestion) as FormattedIssue;
        } catch (fmtErr) {
          if (fmtErr instanceof BamlValidationError) {
            console.warn("[process] FormatAsGitHubIssue failed, retrying with ClaudeSonnet:", (fmtErr as Error).message);
            send({ type: "progress", message: "Retrying format with fallback model…" });
            issueOutput = await b.FormatAsGitHubIssue(issueInput, classification, enrichment, fixSuggestion, { client: "ClaudeSonnet" }) as FormattedIssue;
          } else {
            throw fmtErr;
          }
        }

        // Create GitHub issue
        send({ type: "progress", message: "Creating GitHub issue…" });
        const { data: createdIssue } = await octokit.issues.create({
          owner,
          repo,
          title: issueOutput.github_title,
          body: issueOutput.github_body,
          labels: issueOutput.labels,
          assignees: issueOutput.assignee ? [issueOutput.assignee] : undefined,
        });

        // Persist result
        await supabase.from("panel_issues").insert({
          submission_id: id,
          github_issue_number: createdIssue.number,
          github_issue_url: createdIssue.html_url,
          plain_summary: issueOutput.plain_summary,
          technical_details: { raw: issueOutput.technical_details, priority: issueOutput.priority },
          labels: issueOutput.labels,
        });

        await supabase
          .from("panel_submissions")
          .update({ status: "completed" })
          .eq("id", id);

        send({
          type: "completed",
          message: "Issue created successfully",
          issueUrl: createdIssue.html_url,
          issueNumber: createdIssue.number,
          title: issueOutput.github_title,
          plainSummary: issueOutput.plain_summary,
        });
      } catch (err) {
        console.error("Process pipeline error:", err);
        await supabase
          .from("panel_submissions")
          .update({ status: "failed", error_message: err instanceof Error ? err.message : String(err) })
          .eq("id", id);
        send({ type: "error", message: err instanceof Error ? err.message : "Pipeline failed" });
      }

      controller.close();
    },
  });

  return withCors(new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  }), req);
}
