import { validateApiKey, unauthorized } from "@/lib/auth";
import { getServiceSupabase } from "@/lib/supabase";
import { getGitHubClient, parseRepo } from "@/lib/github";
import { corsPreflight, withCors } from "@/lib/cors";
import type { ConversationTurn, PanelSubmission, SubmissionMetadata } from "@consiliency/panel-types";

export async function OPTIONS(req: Request) { return corsPreflight(req); }

const MAX_TURN_CONTENT_LENGTH = 4000;

/**
 * Sanitize user-supplied transcript content before passing to BAML.
 * Prevents prompt injection via oversized or control-character-laden strings.
 */
function sanitizeTranscript(turns: ConversationTurn[]): ConversationTurn[] {
  return turns.map((turn) => ({
    ...turn,
    content: turn.content
      // eslint-disable-next-line no-control-regex
      .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "") // strip non-printable control chars
      .slice(0, MAX_TURN_CONTENT_LENGTH),
  }));
}

function sseEvent(data: object): string {
  return `data: ${JSON.stringify(data)}\n\n`;
}

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
): Promise<Response> {
  const key = await validateApiKey(req);
  if (!key) return withCors(unauthorized(), req);

  const { id } = await params;
  const body = (await req.json()) as { repo: string };

  const supabase = getServiceSupabase();

  // Mark as processing
  await supabase
    .from("panel_submissions")
    .update({ status: "processing" })
    .eq("id", id);

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: object) => {
        controller.enqueue(encoder.encode(sseEvent(data)));
      };

      try {
        // Fetch the submission
        const { data: submission } = await supabase
          .from("panel_submissions")
          .select("*")
          .eq("id", id)
          .single();

        if (!submission) {
          send({ type: "error", message: "Submission not found" });
          controller.close();
          return;
        }

        const sub = submission as PanelSubmission;

        // Fetch repo context for enrichment
        send({ type: "progress", message: "Gathering repository context…" });

        const { owner, repo } = parseRepo(body.repo);
        const octokit = getGitHubClient(sub.tier as "guest" | "contractor" | "team");

        const [{ data: labels }, { data: issues }] = await Promise.all([
          octokit.issues.listLabelsForRepo({ owner, repo, per_page: 50 }),
          octokit.issues.listForRepo({ owner, repo, state: "open", per_page: 20 }),
        ]);

        const repoContext = {
          labels: labels.map((l) => ({ name: l.name, description: l.description ?? undefined, color: l.color })),
          recentIssues: issues.map((i) => ({ number: i.number, title: i.title, state: i.state, url: i.html_url })),
        };

        send({ type: "progress", message: "Classifying issue…" });

        // Import the BAML client generated by baml-cli generate
        // Path: baml_client/ at repo root → 6 levels up from this route file
        const { b } = await import("baml_client");

        const rawMeta = sub.metadata as SubmissionMetadata;
        const bamlMetadata = {
          ...rawMeta,
          // BAML SubmissionMetadata.viewport is string; serialize the object
          viewport:
            typeof rawMeta.viewport === "object"
              ? `${rawMeta.viewport.width}x${rawMeta.viewport.height}`
              : String(rawMeta.viewport),
        };

        const issueInput = {
          transcript: sanitizeTranscript(sub.transcript as ConversationTurn[]),
          metadata: bamlMetadata,
          repo_context: repoContext,
          tier: sub.tier,
        };

        const classification = await b.ClassifyIssue(issueInput);

        send({ type: "progress", message: "Enriching with context…" });
        const enrichment = await b.EnrichWithRepoContext(issueInput, classification);

        send({ type: "progress", message: "Formatting issue…" });
        const issueOutput = await b.FormatAsGitHubIssue(issueInput, classification, enrichment) as {
          github_title: string;
          github_body: string;
          labels: string[];
          assignee?: string;
          plain_summary: string;
          technical_details: string;
          priority: string;
        };

        // Create GitHub issue
        send({ type: "progress", message: "Creating GitHub issue…" });
        const { data: createdIssue } = await octokit.issues.create({
          owner,
          repo,
          title: issueOutput.github_title,
          body: issueOutput.github_body,
          labels: issueOutput.labels,
          assignees: issueOutput.assignee ? [issueOutput.assignee] : undefined,
        });

        // Persist result
        await supabase.from("panel_issues").insert({
          submission_id: id,
          github_issue_number: createdIssue.number,
          github_issue_url: createdIssue.html_url,
          plain_summary: issueOutput.plain_summary,
          technical_details: { raw: issueOutput.technical_details, priority: issueOutput.priority },
          labels: issueOutput.labels,
        });

        await supabase
          .from("panel_submissions")
          .update({ status: "completed" })
          .eq("id", id);

        send({
          type: "completed",
          message: "Issue created successfully",
          issueUrl: createdIssue.html_url,
          issueNumber: createdIssue.number,
          title: issueOutput.github_title,
          plainSummary: issueOutput.plain_summary,
        });
      } catch (err) {
        console.error("Process pipeline error:", err);
        await supabase
          .from("panel_submissions")
          .update({ status: "failed" })
          .eq("id", id);
        send({ type: "error", message: err instanceof Error ? err.message : "Pipeline failed" });
      }

      controller.close();
    },
  });

  return withCors(new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  }), req);
}
