/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AttachmentRef,  ConversationTurn,  FixSuggestion,  IssueClassification,  IssueInput,  IssueLabel,  IssueOutput,  NavigationEntry,  RepoContext,  RepoEnrichment,  RepoIssue,  RepoLabel,  SubmissionMetadata } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AttachmentRef {
      url?: string | null
      type?: string | null
      name?: string | null
    }
    export interface ConversationTurn {
      role?: string | null
      content?: string | null
      timestamp?: string | null
    }
    export interface FixSuggestion {
      relevant_functions: string[]
      root_cause?: string | null
      suggested_approach?: string | null
      code_hint?: string | null
      confidence?: string | null
    }
    export interface IssueClassification {
      category?: string | null
      severity?: string | null
      labels: IssueLabel[]
      requires_reproduction?: boolean | null
    }
    export interface IssueInput {
      transcript: ConversationTurn[]
      metadata?: SubmissionMetadata | null
      repo_context?: RepoContext | null
      tier?: string | null
      console_errors?: string[] | null
      navigation_breadcrumb?: NavigationEntry[] | null
      component_hint?: string | null
      attachment_urls?: AttachmentRef[] | null
    }
    export interface IssueLabel {
      name?: string | null
      reason?: string | null
    }
    export interface IssueOutput {
      plain_summary?: string | null
      technical_details?: string | null
      github_title?: string | null
      github_body?: string | null
      labels: string[]
      assignee?: string | null
      priority?: string | null
      fix_suggestion?: FixSuggestion | null
    }
    export interface NavigationEntry {
      url?: string | null
      title?: string | null
      timestamp?: string | null
    }
    export interface RepoContext {
      labels?: RepoLabel[] | null
      recentIssues?: RepoIssue[] | null
      relevantFiles?: string[] | null
      file_contents?: Record<string, string> | null
    }
    export interface RepoEnrichment {
      relevant_files: string[]
      related_issues: string[]
      suggested_assignee?: string | null
      reproduction_steps: string[]
    }
    export interface RepoIssue {
      number?: number | null
      title?: string | null
      state?: string | null
      url?: string | null
    }
    export interface RepoLabel {
      name?: string | null
      description?: string | null
      color?: string | null
    }
    export interface SubmissionMetadata {
      url?: string | null
      title?: string | null
      userAgent?: string | null
      viewport?: string | null
      timestamp?: string | null
    }
}