/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, Collector, FunctionLog } from "@boundaryml/baml"
import { toBamlError, BamlAbortError, ClientRegistry, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type * as types from "./types"
import type {AttachmentRef, ConversationTurn, FixSuggestion, IssueClassification, IssueDraftIn, IssueDraftOut, IssueInput, IssueLabel, IssueOutput, KnownFactsInput, NavigationEntry, OnTopicResult, PreSubmitResult, RepoContext, RepoEnrichment, RepoIssue, RepoLabel, RoutingDecision, SubmissionMetadata, ToolCallOut, Viewport} from "./types"
import type TypeBuilder from "./type_builder"
import { HttpRequest, HttpStreamRequest } from "./sync_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type TickReason = "Unknown";

type BamlCallOptions<WatchersT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
  tags?: Record<string, string>
  signal?: AbortSignal
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  watchers?: WatchersT
}

export class BamlSyncClient {
  private httpRequest: HttpRequest
  private httpStreamRequest: HttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.httpRequest = new HttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new HttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlSyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  ClassifyIssue(
      input: types.IssueInput,
      __baml_options__?: BamlCallOptions<never>
  ): types.IssueClassification {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ClassifyIssue",
        {
          "input": input
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.IssueClassification
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  EnrichWithRepoContext(
      input: types.IssueInput,classification: types.IssueClassification,
      __baml_options__?: BamlCallOptions<never>
  ): types.RepoEnrichment {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "EnrichWithRepoContext",
        {
          "input": input,"classification": classification
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.RepoEnrichment
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  FormatAsGitHubIssue(
      input: types.IssueInput,classification: types.IssueClassification,enrichment: types.RepoEnrichment,fix_suggestion?: types.FixSuggestion | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.IssueOutput {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "FormatAsGitHubIssue",
        {
          "input": input,"classification": classification,"enrichment": enrichment,"fix_suggestion": fix_suggestion?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.IssueOutput
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  IsOnTopic(
      message: string,app_context: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.OnTopicResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "IsOnTopic",
        {
          "message": message,"app_context": app_context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.OnTopicResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  IsReadyToSubmit(
      draft: types.IssueDraftIn,
      __baml_options__?: BamlCallOptions<never>
  ): types.PreSubmitResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "IsReadyToSubmit",
        {
          "draft": draft
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PreSubmitResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  NextCommentTurn(
      issue_body: string,transcript: types.ConversationTurn[],known_facts: types.KnownFactsInput,app_context: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolCallOut {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "NextCommentTurn",
        {
          "issue_body": issue_body,"transcript": transcript,"known_facts": known_facts,"app_context": app_context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolCallOut
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  NextTurn(
      known_facts: types.KnownFactsInput,transcript: types.ConversationTurn[],metadata: types.SubmissionMetadata,app_context: string,screenshot_url?: string | null,selected_kind?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolCallOut {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "NextTurn",
        {
          "known_facts": known_facts,"transcript": transcript,"metadata": metadata,"app_context": app_context,"screenshot_url": screenshot_url?? null,"selected_kind": selected_kind?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolCallOut
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RouteToRepo(
      transcript: types.ConversationTurn[],metadata: types.SubmissionMetadata,retained_screenshot_kinds: string[],
      __baml_options__?: BamlCallOptions<never>
  ): types.RoutingDecision {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RouteToRepo",
        {
          "transcript": transcript,"metadata": metadata,"retained_screenshot_kinds": retained_screenshot_kinds
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.RoutingDecision
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SuggestFix(
      input: types.IssueInput,classification: types.IssueClassification,enrichment: types.RepoEnrichment,
      __baml_options__?: BamlCallOptions<never>
  ): types.FixSuggestion {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SuggestFix",
        {
          "input": input,"classification": classification,"enrichment": enrichment
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.FixSuggestion
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  UpdateKnownFacts(
      prior: types.KnownFactsInput,latest_user_turn: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.KnownFactsInput {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "UpdateKnownFacts",
        {
          "prior": prior,"latest_user_turn": latest_user_turn
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.KnownFactsInput
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)