/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AttachmentRef: ClassViewer<'AttachmentRef', "url" | "type" | "name">;
    
    ConversationTurn: ClassViewer<'ConversationTurn', "role" | "content" | "timestamp">;
    
    FixSuggestion: ClassViewer<'FixSuggestion', "relevant_functions" | "root_cause" | "suggested_approach" | "code_hint" | "confidence">;
    
    IssueClassification: ClassViewer<'IssueClassification', "category" | "severity" | "labels" | "requires_reproduction">;
    
    IssueDraftIn: ClassViewer<'IssueDraftIn', "title" | "body" | "severity" | "kind">;
    
    IssueDraftOut: ClassViewer<'IssueDraftOut', "title" | "body" | "severity" | "kind">;
    
    IssueInput: ClassViewer<'IssueInput', "transcript" | "metadata" | "repo_context" | "tier" | "console_errors" | "console_warnings" | "navigation_breadcrumb" | "component_hint" | "attachment_urls">;
    
    IssueLabel: ClassViewer<'IssueLabel', "name" | "reason">;
    
    IssueOutput: ClassViewer<'IssueOutput', "plain_summary" | "technical_details" | "github_title" | "github_body" | "labels" | "assignee" | "priority" | "fix_suggestion">;
    
    KnownFactsInput: ClassViewer<'KnownFactsInput', "action" | "actual" | "expected" | "severity" | "repro_steps" | "first_seen" | "frequency" | "kind">;
    
    NavigationEntry: ClassViewer<'NavigationEntry', "url" | "title" | "timestamp">;
    
    OnTopicResult: ClassViewer<'OnTopicResult', "on_topic" | "redirect_hint">;
    
    PreSubmitResult: ClassViewer<'PreSubmitResult', "ready" | "reason">;
    
    RepoContext: ClassViewer<'RepoContext', "labels" | "recentIssues" | "relevantFiles" | "file_contents">;
    
    RepoEnrichment: ClassViewer<'RepoEnrichment', "relevant_files" | "related_issues" | "suggested_assignee" | "reproduction_steps">;
    
    RepoIssue: ClassViewer<'RepoIssue', "number" | "title" | "state" | "url">;
    
    RepoLabel: ClassViewer<'RepoLabel', "name" | "description" | "color">;
    
    RoutingDecision: ClassViewer<'RoutingDecision', "target" | "reasoning" | "confidence">;
    
    SubmissionMetadata: ClassViewer<'SubmissionMetadata', "url" | "title" | "userAgent" | "viewport" | "timestamp">;
    
    ToolCallOut: ClassViewer<'ToolCallOut', "type" | "question" | "reason" | "options" | "redirect" | "draft">;
    
    Viewport: ClassViewer<'Viewport', "width" | "height">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AttachmentRef","ConversationTurn","FixSuggestion","IssueClassification","IssueDraftIn","IssueDraftOut","IssueInput","IssueLabel","IssueOutput","KnownFactsInput","NavigationEntry","OnTopicResult","PreSubmitResult","RepoContext","RepoEnrichment","RepoIssue","RepoLabel","RoutingDecision","SubmissionMetadata","ToolCallOut","Viewport",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AttachmentRef = this.tb.classViewer("AttachmentRef", [
          "url","type","name",
        ]);
        
        this.ConversationTurn = this.tb.classViewer("ConversationTurn", [
          "role","content","timestamp",
        ]);
        
        this.FixSuggestion = this.tb.classViewer("FixSuggestion", [
          "relevant_functions","root_cause","suggested_approach","code_hint","confidence",
        ]);
        
        this.IssueClassification = this.tb.classViewer("IssueClassification", [
          "category","severity","labels","requires_reproduction",
        ]);
        
        this.IssueDraftIn = this.tb.classViewer("IssueDraftIn", [
          "title","body","severity","kind",
        ]);
        
        this.IssueDraftOut = this.tb.classViewer("IssueDraftOut", [
          "title","body","severity","kind",
        ]);
        
        this.IssueInput = this.tb.classViewer("IssueInput", [
          "transcript","metadata","repo_context","tier","console_errors","console_warnings","navigation_breadcrumb","component_hint","attachment_urls",
        ]);
        
        this.IssueLabel = this.tb.classViewer("IssueLabel", [
          "name","reason",
        ]);
        
        this.IssueOutput = this.tb.classViewer("IssueOutput", [
          "plain_summary","technical_details","github_title","github_body","labels","assignee","priority","fix_suggestion",
        ]);
        
        this.KnownFactsInput = this.tb.classViewer("KnownFactsInput", [
          "action","actual","expected","severity","repro_steps","first_seen","frequency","kind",
        ]);
        
        this.NavigationEntry = this.tb.classViewer("NavigationEntry", [
          "url","title","timestamp",
        ]);
        
        this.OnTopicResult = this.tb.classViewer("OnTopicResult", [
          "on_topic","redirect_hint",
        ]);
        
        this.PreSubmitResult = this.tb.classViewer("PreSubmitResult", [
          "ready","reason",
        ]);
        
        this.RepoContext = this.tb.classViewer("RepoContext", [
          "labels","recentIssues","relevantFiles","file_contents",
        ]);
        
        this.RepoEnrichment = this.tb.classViewer("RepoEnrichment", [
          "relevant_files","related_issues","suggested_assignee","reproduction_steps",
        ]);
        
        this.RepoIssue = this.tb.classViewer("RepoIssue", [
          "number","title","state","url",
        ]);
        
        this.RepoLabel = this.tb.classViewer("RepoLabel", [
          "name","description","color",
        ]);
        
        this.RoutingDecision = this.tb.classViewer("RoutingDecision", [
          "target","reasoning","confidence",
        ]);
        
        this.SubmissionMetadata = this.tb.classViewer("SubmissionMetadata", [
          "url","title","userAgent","viewport","timestamp",
        ]);
        
        this.ToolCallOut = this.tb.classViewer("ToolCallOut", [
          "type","question","reason","options","redirect","draft",
        ]);
        
        this.Viewport = this.tb.classViewer("Viewport", [
          "width","height",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}