/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AttachmentRef {
  url: string
  type: string
  name: string
  
}

export interface ConversationTurn {
  role: string
  content: string
  timestamp?: string | null
  
}

export interface FixSuggestion {
  relevant_functions: string[]
  root_cause: string
  suggested_approach: string
  code_hint?: string | null
  confidence: string
  
}

export interface IssueClassification {
  category: string
  severity: string
  labels: IssueLabel[]
  requires_reproduction: boolean
  
}

export interface IssueInput {
  transcript: ConversationTurn[]
  metadata: SubmissionMetadata
  repo_context?: RepoContext | null
  tier: string
  console_errors?: string[] | null
  navigation_breadcrumb?: NavigationEntry[] | null
  component_hint?: string | null
  attachment_urls?: AttachmentRef[] | null
  
}

export interface IssueLabel {
  name: string
  reason: string
  
}

export interface IssueOutput {
  plain_summary: string
  technical_details: string
  github_title: string
  github_body: string
  labels: string[]
  assignee?: string | null
  priority: string
  fix_suggestion?: FixSuggestion | null
  
}

export interface NavigationEntry {
  url: string
  title: string
  timestamp: string
  
}

export interface RepoContext {
  labels?: RepoLabel[] | null
  recentIssues?: RepoIssue[] | null
  relevantFiles?: string[] | null
  file_contents?: Record<string, string> | null
  
}

export interface RepoEnrichment {
  relevant_files: string[]
  related_issues: string[]
  suggested_assignee?: string | null
  reproduction_steps: string[]
  
}

export interface RepoIssue {
  number: number
  title: string
  state: string
  url: string
  
}

export interface RepoLabel {
  name: string
  description?: string | null
  color: string
  
}

export interface SubmissionMetadata {
  url: string
  title: string
  userAgent: string
  viewport: string
  timestamp: string
  
}
